name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Wymuszenie użycia Node 24 dla wszystkich akcji w tym pliku
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/postgres-ha:latest"
        
        echo "Budowanie obrazu: $IMAGE_NAME"
        docker build . --file Dockerfile --tag "$IMAGE_NAME"
        
        echo "Wysyłanie obrazu do Docker Hub..."
        docker push "$IMAGE_NAME"
